manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: git@github.com:zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 545c2870e9358d52e319b9ae301845e053376fe1
      import: true
  self:
    path: origin
