manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: git@github.com:zephyrproject-rtos
    - name: thermoquad
      url-base: git@github.com:Thermoquad
  projects:
    - name: zephyr
      remote: thermoquad
      revision: feat/bt-hci-cyw43-shared-bus
      import: true
    - name: zephyr-cyw43-bt
      remote: thermoquad
      revision: main
      path: modules/lib/zephyr-cyw43-bt
  self:
    path: origin
